import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { uiConfig } from "@/config/ui.config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const activeTheme =
    uiConfig.themeMode === "dark" ? uiConfig.dark : uiConfig.light;

  return (
    <html
      lang="en"
      className={uiConfig.themeMode === "dark" ? "dark" : ""}
      style={
        {
          "--primary": activeTheme.primary,
          "--background": activeTheme.background,
          "--foreground": activeTheme.foreground,
        } as React.CSSProperties
      }
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
