export const palettes = {
  default: {
    light: {
      primary: "#ff781f",
      primaryForeground: "#ffffff",

      secondary: "#f1f5f9",
      secondaryForeground: "#0f172a",

      background: "#ffffff",
      foreground: "#0f172a",

      muted: "#f3f4f6",
      mutedForeground: "#6b7280",

      border: "#e5e7eb",

      table: {
        headerBg: "#f3f4f6",
        rowHover: "#e5e7eb",
        rowAlternate: "#fafafa",
        selectedRow: "#e8f0ff",
      },

      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },

    dark: {
      primary: "#ff781f",
      primaryForeground: "#000000",

      secondary: "#1f2937",
      secondaryForeground: "#f9fafb",

      background: "#0f172a",
      foreground: "#f8fafc",

      muted: "#1e293b",
      mutedForeground: "#94a3b8",

      border: "#334155",

      table: {
        headerBg: "#1e293b",
        rowHover: "#334155",
        rowAlternate: "#172033",
        selectedRow: "#1d2c52",
      },

      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#94a3b8",
      },
    },
  },
  // 🌊 1. Ocean Mint
  oceanMint: {
    light: {
      primary: "#0A9396",
      primaryForeground: "#ffffff",
      secondary: "#94D2BD",
      secondaryForeground: "#0f172a",
      background: "#F1FAEE",
      foreground: "#0f172a",
      muted: "#E6F4F1",
      mutedForeground: "#4b5563",
      border: "#d1d5db",
      table: {
        headerBg: "#E6F4F1",
        rowHover: "#94D2BD",
        rowAlternate: "#F8FFFD",
        selectedRow: "#DFF6F2",
      },
      brand: {
        success: "#2A9D8F",
        warning: "#E9C46A",
        danger: "#E76F51",
        info: "#0EA5E9",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#0A9396",
      primaryForeground: "#000000",
      secondary: "#005F73",
      secondaryForeground: "#ecfeff",
      background: "#0b1f24",
      foreground: "#e6fffa",
      muted: "#12343b",
      mutedForeground: "#94a3b8",
      border: "#1f4d57",
      table: {
        headerBg: "#12343b",
        rowHover: "#0A9396",
        rowAlternate: "#0f2a30",
        selectedRow: "#134e4a",
      },
      brand: {
        success: "#2A9D8F",
        warning: "#E9C46A",
        danger: "#E76F51",
        info: "#38bdf8",
        neutral: "#94a3b8",
      },
    },
  },

  // 🔥 2. Sunset Pink
  sunsetPink: {
    light: {
      primary: "#DC586D",
      primaryForeground: "#ffffff",
      secondary: "#FBBF94",
      secondaryForeground: "#0f172a",
      background: "#FFF1E6",
      foreground: "#0f172a",
      muted: "#FFE4D6",
      mutedForeground: "#6b7280",
      border: "#f1d5c7",
      table: {
        headerBg: "#FFE4D6",
        rowHover: "#FBBF94",
        rowAlternate: "#fff7f2",
        selectedRow: "#ffd6c9",
      },
      brand: {
        success: "#22c55e",
        warning: "#fb923c",
        danger: "#DC2626",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#DC586D",
      primaryForeground: "#000000",
      secondary: "#7A3350",
      secondaryForeground: "#ffe4e6",
      background: "#1a0f14",
      foreground: "#ffe4e6",
      muted: "#2a1620",
      mutedForeground: "#9ca3af",
      border: "#3f1f2b",
      table: {
        headerBg: "#2a1620",
        rowHover: "#DC586D",
        rowAlternate: "#22131a",
        selectedRow: "#3b1f29",
      },
      brand: {
        success: "#22c55e",
        warning: "#fb923c",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🌿 3. Olive Earth
  olive: {
    light: {
      primary: "#606C38",
      primaryForeground: "#ffffff",
      secondary: "#DDA15E",
      secondaryForeground: "#1c1917",
      background: "#FEFAE0",
      foreground: "#1c1917",
      muted: "#F3EEDC",
      mutedForeground: "#6b7280",
      border: "#e7d7b1",
      table: {
        headerBg: "#F3EEDC",
        rowHover: "#DDA15E",
        rowAlternate: "#fffdf5",
        selectedRow: "#f5e6c8",
      },
      brand: {
        success: "#4CAF50",
        warning: "#DDA15E",
        danger: "#BC4749",
        info: "#3b82f6",
        neutral: "#6b7280",
      },
    },
    dark: {
      primary: "#606C38",
      primaryForeground: "#ffffff",
      secondary: "#283618",
      secondaryForeground: "#ecfccb",
      background: "#0f140f",
      foreground: "#f7fee7",
      muted: "#1a231a",
      mutedForeground: "#9ca3af",
      border: "#2f3e2f",
      table: {
        headerBg: "#1a231a",
        rowHover: "#606C38",
        rowAlternate: "#141c14",
        selectedRow: "#2a3b2a",
      },
      brand: {
        success: "#4CAF50",
        warning: "#DDA15E",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🔵 4. Deep Blue
  deepBlue: {
    light: {
      primary: "#2563EB",
      primaryForeground: "#ffffff",
      secondary: "#DBEAFE",
      secondaryForeground: "#1e3a8a",
      background: "#F8FAFC",
      foreground: "#0f172a",
      muted: "#EFF6FF",
      mutedForeground: "#64748b",
      border: "#e2e8f0",
      table: {
        headerBg: "#EFF6FF",
        rowHover: "#DBEAFE",
        rowAlternate: "#f8fafc",
        selectedRow: "#dbeafe",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#2563EB",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#3B82F6",
      primaryForeground: "#000000",
      secondary: "#1E3A8A",
      secondaryForeground: "#DBEAFE",
      background: "#020617",
      foreground: "#E2E8F0",
      muted: "#0f172a",
      mutedForeground: "#94a3b8",
      border: "#1e293b",
      table: {
        headerBg: "#0f172a",
        rowHover: "#1d4ed8",
        rowAlternate: "#020617",
        selectedRow: "#1e40af",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#94a3b8",
      },
    },
  },

  // 🟣 5. Purple Neon
  purpleNeon: {
    light: {
      primary: "#7C3AED",
      primaryForeground: "#ffffff",
      secondary: "#E9D5FF",
      secondaryForeground: "#4c1d95",
      background: "#FAF5FF",
      foreground: "#1e1b4b",
      muted: "#F3E8FF",
      mutedForeground: "#6b7280",
      border: "#e9d5ff",
      table: {
        headerBg: "#F3E8FF",
        rowHover: "#E9D5FF",
        rowAlternate: "#faf5ff",
        selectedRow: "#e9d5ff",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#7C3AED",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#8B5CF6",
      primaryForeground: "#000000",
      secondary: "#4C1D95",
      secondaryForeground: "#E9D5FF",
      background: "#0f0a1f",
      foreground: "#EDE9FE",
      muted: "#1e1b2e",
      mutedForeground: "#9ca3af",
      border: "#312e81",
      table: {
        headerBg: "#1e1b2e",
        rowHover: "#7C3AED",
        rowAlternate: "#140f2a",
        selectedRow: "#2e1f66",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#a78bfa",
        neutral: "#9ca3af",
      },
    },
  },

  // ❤️ 6. Red Crimson
  crimson: {
    light: {
      primary: "#DC2626",
      primaryForeground: "#ffffff",
      secondary: "#FECACA",
      secondaryForeground: "#7f1d1d",
      background: "#FEF2F2",
      foreground: "#1c1917",
      muted: "#FEE2E2",
      mutedForeground: "#6b7280",
      border: "#fecaca",
      table: {
        headerBg: "#FEE2E2",
        rowHover: "#FCA5A5",
        rowAlternate: "#fff5f5",
        selectedRow: "#fecaca",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#DC2626",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#EF4444",
      primaryForeground: "#000000",
      secondary: "#7F1D1D",
      secondaryForeground: "#FECACA",
      background: "#140909",
      foreground: "#FEE2E2",
      muted: "#2a0f0f",
      mutedForeground: "#9ca3af",
      border: "#450a0a",
      table: {
        headerBg: "#2a0f0f",
        rowHover: "#DC2626",
        rowAlternate: "#1a0c0c",
        selectedRow: "#3b1212",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🟡 7. Golden Amber
  goldenAmber: {
    light: {
      primary: "#F59E0B",
      primaryForeground: "#ffffff",
      secondary: "#FEF3C7",
      secondaryForeground: "#78350f",
      background: "#FFFBEB",
      foreground: "#1c1917",
      muted: "#FEF3C7",
      mutedForeground: "#6b7280",
      border: "#fde68a",
      table: {
        headerBg: "#FEF3C7",
        rowHover: "#FCD34D",
        rowAlternate: "#fffbea",
        selectedRow: "#fde68a",
      },
      brand: {
        success: "#22c55e",
        warning: "#F59E0B",
        danger: "#ef4444",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#FBBF24",
      primaryForeground: "#000000",
      secondary: "#78350F",
      secondaryForeground: "#FEF3C7",
      background: "#1a1203",
      foreground: "#FEF3C7",
      muted: "#2a1c05",
      mutedForeground: "#9ca3af",
      border: "#451a03",
      table: {
        headerBg: "#2a1c05",
        rowHover: "#F59E0B",
        rowAlternate: "#140d02",
        selectedRow: "#3b2a06",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 💗 8. Soft Pink
  softPink: {
    light: {
      primary: "#EC4899",
      primaryForeground: "#ffffff",
      secondary: "#FBCFE8",
      secondaryForeground: "#831843",
      background: "#FDF2F8",
      foreground: "#1c1917",
      muted: "#FCE7F3",
      mutedForeground: "#6b7280",
      border: "#fbcfe8",
      table: {
        headerBg: "#FCE7F3",
        rowHover: "#FBCFE8",
        rowAlternate: "#fff5fa",
        selectedRow: "#fbcfe8",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#EC4899",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#F472B6",
      primaryForeground: "#000000",
      secondary: "#831843",
      secondaryForeground: "#FBCFE8",
      background: "#1a0f16",
      foreground: "#FCE7F3",
      muted: "#2a1722",
      mutedForeground: "#9ca3af",
      border: "#500724",
      table: {
        headerBg: "#2a1722",
        rowHover: "#EC4899",
        rowAlternate: "#1a0f16",
        selectedRow: "#3b1f2d",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f472b6",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🟢 9. Emerald Fresh
  emerald: {
    light: {
      primary: "#10B981",
      primaryForeground: "#ffffff",
      secondary: "#D1FAE5",
      secondaryForeground: "#064e3b",
      background: "#ECFDF5",
      foreground: "#022c22",
      muted: "#D1FAE5",
      mutedForeground: "#6b7280",
      border: "#a7f3d0",
      table: {
        headerBg: "#D1FAE5",
        rowHover: "#6EE7B7",
        rowAlternate: "#f0fdf4",
        selectedRow: "#a7f3d0",
      },
      brand: {
        success: "#10B981",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#34D399",
      primaryForeground: "#000000",
      secondary: "#064E3B",
      secondaryForeground: "#D1FAE5",
      background: "#02120d",
      foreground: "#D1FAE5",
      muted: "#03251b",
      mutedForeground: "#9ca3af",
      border: "#064e3b",
      table: {
        headerBg: "#03251b",
        rowHover: "#10B981",
        rowAlternate: "#02120d",
        selectedRow: "#064e3b",
      },
      brand: {
        success: "#34D399",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🧊 10. Ice Blue
  iceBlue: {
    light: {
      primary: "#38BDF8",
      primaryForeground: "#ffffff",
      secondary: "#E0F2FE",
      secondaryForeground: "#075985",
      background: "#F0F9FF",
      foreground: "#0c4a6e",
      muted: "#E0F2FE",
      mutedForeground: "#6b7280",
      border: "#bae6fd",
      table: {
        headerBg: "#E0F2FE",
        rowHover: "#7DD3FC",
        rowAlternate: "#f8fcff",
        selectedRow: "#bae6fd",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#38BDF8",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#0EA5E9",
      primaryForeground: "#000000",
      secondary: "#075985",
      secondaryForeground: "#E0F2FE",
      background: "#03131a",
      foreground: "#E0F2FE",
      muted: "#082a36",
      mutedForeground: "#9ca3af",
      border: "#0c4a6e",
      table: {
        headerBg: "#082a36",
        rowHover: "#38BDF8",
        rowAlternate: "#03131a",
        selectedRow: "#075985",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#38BDF8",
        neutral: "#9ca3af",
      },
    },
  },

  // 🟤 11. Coffee Brown
  coffee: {
    light: {
      primary: "#8B5E3C",
      primaryForeground: "#ffffff",
      secondary: "#EADBC8",
      secondaryForeground: "#3e2723",
      background: "#FDF6F0",
      foreground: "#3e2723",
      muted: "#F5EDE4",
      mutedForeground: "#6b7280",
      border: "#e0cfc0",
      table: {
        headerBg: "#F5EDE4",
        rowHover: "#EADBC8",
        rowAlternate: "#fffaf5",
        selectedRow: "#e0cfc0",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#A47148",
      primaryForeground: "#000000",
      secondary: "#3E2723",
      secondaryForeground: "#EADBC8",
      background: "#1a120e",
      foreground: "#F5EDE4",
      muted: "#2a1d18",
      mutedForeground: "#9ca3af",
      border: "#4e342e",
      table: {
        headerBg: "#2a1d18",
        rowHover: "#8B5E3C",
        rowAlternate: "#1a120e",
        selectedRow: "#3e2723",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // ⚫ 12. Graphite Dark
  graphite: {
    light: {
      primary: "#374151",
      primaryForeground: "#ffffff",
      secondary: "#E5E7EB",
      secondaryForeground: "#111827",
      background: "#F9FAFB",
      foreground: "#111827",
      muted: "#F3F4F6",
      mutedForeground: "#6b7280",
      border: "#e5e7eb",
      table: {
        headerBg: "#F3F4F6",
        rowHover: "#E5E7EB",
        rowAlternate: "#fafafa",
        selectedRow: "#e5e7eb",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#3b82f6",
        neutral: "#6b7280",
      },
    },
    dark: {
      primary: "#9CA3AF",
      primaryForeground: "#000000",
      secondary: "#1F2937",
      secondaryForeground: "#F9FAFB",
      background: "#030712",
      foreground: "#E5E7EB",
      muted: "#111827",
      mutedForeground: "#9ca3af",
      border: "#1f2937",
      table: {
        headerBg: "#111827",
        rowHover: "#374151",
        rowAlternate: "#030712",
        selectedRow: "#1f2937",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🌈 13. Indigo Night
  indigo: {
    light: {
      primary: "#4F46E5",
      primaryForeground: "#ffffff",
      secondary: "#E0E7FF",
      secondaryForeground: "#312e81",
      background: "#EEF2FF",
      foreground: "#1e1b4b",
      muted: "#E0E7FF",
      mutedForeground: "#6b7280",
      border: "#c7d2fe",
      table: {
        headerBg: "#E0E7FF",
        rowHover: "#C7D2FE",
        rowAlternate: "#f5f7ff",
        selectedRow: "#c7d2fe",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#4F46E5",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#6366F1",
      primaryForeground: "#000000",
      secondary: "#312E81",
      secondaryForeground: "#E0E7FF",
      background: "#0c0d2a",
      foreground: "#E0E7FF",
      muted: "#1a1b3a",
      mutedForeground: "#9ca3af",
      border: "#312e81",
      table: {
        headerBg: "#1a1b3a",
        rowHover: "#4F46E5",
        rowAlternate: "#0c0d2a",
        selectedRow: "#312e81",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#818cf8",
        neutral: "#9ca3af",
      },
    },
  },

  // 🍇 14. Grape Wine
  grape: {
    light: {
      primary: "#7E22CE",
      primaryForeground: "#ffffff",
      secondary: "#F3E8FF",
      secondaryForeground: "#581c87",
      background: "#FAF5FF",
      foreground: "#3b0764",
      muted: "#F3E8FF",
      mutedForeground: "#6b7280",
      border: "#e9d5ff",
      table: {
        headerBg: "#F3E8FF",
        rowHover: "#E9D5FF",
        rowAlternate: "#faf5ff",
        selectedRow: "#e9d5ff",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#7E22CE",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#A855F7",
      primaryForeground: "#000000",
      secondary: "#581C87",
      secondaryForeground: "#F3E8FF",
      background: "#140a1f",
      foreground: "#F3E8FF",
      muted: "#24112f",
      mutedForeground: "#9ca3af",
      border: "#581c87",
      table: {
        headerBg: "#24112f",
        rowHover: "#7E22CE",
        rowAlternate: "#140a1f",
        selectedRow: "#3b1d5a",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#c084fc",
        neutral: "#9ca3af",
      },
    },
  },

  // 🌅 15. Peach Orange
  peach: {
    light: {
      primary: "#FB923C",
      primaryForeground: "#ffffff",
      secondary: "#FED7AA",
      secondaryForeground: "#7c2d12",
      background: "#FFF7ED",
      foreground: "#431407",
      muted: "#FFEDD5",
      mutedForeground: "#6b7280",
      border: "#fdba74",
      table: {
        headerBg: "#FFEDD5",
        rowHover: "#FDBA74",
        rowAlternate: "#fffaf5",
        selectedRow: "#fdba74",
      },
      brand: {
        success: "#22c55e",
        warning: "#FB923C",
        danger: "#ef4444",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#FB923C",
      primaryForeground: "#000000",
      secondary: "#7C2D12",
      secondaryForeground: "#FED7AA",
      background: "#1a0f07",
      foreground: "#FFEDD5",
      muted: "#2a1a0f",
      mutedForeground: "#9ca3af",
      border: "#7c2d12",
      table: {
        headerBg: "#2a1a0f",
        rowHover: "#FB923C",
        rowAlternate: "#1a0f07",
        selectedRow: "#3b2415",
      },
      brand: {
        success: "#22c55e",
        warning: "#FB923C",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🌌 16. Midnight Blue
  midnight: {
    light: {
      primary: "#1E3A8A",
      primaryForeground: "#ffffff",
      secondary: "#DBEAFE",
      secondaryForeground: "#1e3a8a",
      background: "#F8FAFC",
      foreground: "#0f172a",
      muted: "#EFF6FF",
      mutedForeground: "#64748b",
      border: "#e2e8f0",
      table: {
        headerBg: "#EFF6FF",
        rowHover: "#DBEAFE",
        rowAlternate: "#f8fafc",
        selectedRow: "#dbeafe",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#1E3A8A",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#1E40AF",
      primaryForeground: "#ffffff",
      secondary: "#1E3A8A",
      secondaryForeground: "#DBEAFE",
      background: "#020617",
      foreground: "#E2E8F0",
      muted: "#0f172a",
      mutedForeground: "#94a3b8",
      border: "#1e293b",
      table: {
        headerBg: "#0f172a",
        rowHover: "#1e40af",
        rowAlternate: "#020617",
        selectedRow: "#1e3a8a",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#94a3b8",
      },
    },
  },

  // ⚡ 17. Neon Green
  neonGreen: {
    light: {
      primary: "#22C55E",
      primaryForeground: "#ffffff",
      secondary: "#DCFCE7",
      secondaryForeground: "#065f46",
      background: "#F0FDF4",
      foreground: "#022c22",
      muted: "#DCFCE7",
      mutedForeground: "#6b7280",
      border: "#bbf7d0",
      table: {
        headerBg: "#DCFCE7",
        rowHover: "#86EFAC",
        rowAlternate: "#f7fff9",
        selectedRow: "#bbf7d0",
      },
      brand: {
        success: "#22C55E",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#4ADE80",
      primaryForeground: "#000000",
      secondary: "#065F46",
      secondaryForeground: "#DCFCE7",
      background: "#022c22",
      foreground: "#DCFCE7",
      muted: "#033c2c",
      mutedForeground: "#9ca3af",
      border: "#065f46",
      table: {
        headerBg: "#033c2c",
        rowHover: "#22C55E",
        rowAlternate: "#022c22",
        selectedRow: "#065f46",
      },
      brand: {
        success: "#4ADE80",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 👑 18. Royal Purple
  royalPurple: {
    light: {
      primary: "#6D28D9",
      primaryForeground: "#ffffff",
      secondary: "#EDE9FE",
      secondaryForeground: "#4c1d95",
      background: "#F5F3FF",
      foreground: "#1e1b4b",
      muted: "#EDE9FE",
      mutedForeground: "#6b7280",
      border: "#ddd6fe",
      table: {
        headerBg: "#EDE9FE",
        rowHover: "#C4B5FD",
        rowAlternate: "#faf5ff",
        selectedRow: "#ddd6fe",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#6D28D9",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#8B5CF6",
      primaryForeground: "#000000",
      secondary: "#4C1D95",
      secondaryForeground: "#EDE9FE",
      background: "#0f0a1f",
      foreground: "#EDE9FE",
      muted: "#1e1b2e",
      mutedForeground: "#9ca3af",
      border: "#312e81",
      table: {
        headerBg: "#1e1b2e",
        rowHover: "#6D28D9",
        rowAlternate: "#140f2a",
        selectedRow: "#2e1f66",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#a78bfa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🌊 19. Aqua Fresh
  aqua: {
    light: {
      primary: "#06B6D4",
      primaryForeground: "#ffffff",
      secondary: "#CFFAFE",
      secondaryForeground: "#164e63",
      background: "#ECFEFF",
      foreground: "#083344",
      muted: "#CFFAFE",
      mutedForeground: "#6b7280",
      border: "#a5f3fc",
      table: {
        headerBg: "#CFFAFE",
        rowHover: "#67E8F9",
        rowAlternate: "#f0fdff",
        selectedRow: "#a5f3fc",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#06B6D4",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#22D3EE",
      primaryForeground: "#000000",
      secondary: "#164E63",
      secondaryForeground: "#CFFAFE",
      background: "#022c33",
      foreground: "#CFFAFE",
      muted: "#083344",
      mutedForeground: "#9ca3af",
      border: "#164e63",
      table: {
        headerBg: "#083344",
        rowHover: "#06B6D4",
        rowAlternate: "#022c33",
        selectedRow: "#164e63",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#67e8f9",
        neutral: "#9ca3af",
      },
    },
  },

  // 🌸 20. Rose Soft
  roseSoft: {
    light: {
      primary: "#F43F5E",
      primaryForeground: "#ffffff",
      secondary: "#FFE4E6",
      secondaryForeground: "#881337",
      background: "#FFF1F2",
      foreground: "#4c0519",
      muted: "#FFE4E6",
      mutedForeground: "#6b7280",
      border: "#fecdd3",
      table: {
        headerBg: "#FFE4E6",
        rowHover: "#FDA4AF",
        rowAlternate: "#fff5f6",
        selectedRow: "#fecdd3",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#F43F5E",
        info: "#3b82f6",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#FB7185",
      primaryForeground: "#000000",
      secondary: "#881337",
      secondaryForeground: "#FFE4E6",
      background: "#1a0a0e",
      foreground: "#FFE4E6",
      muted: "#2a1418",
      mutedForeground: "#9ca3af",
      border: "#881337",
      table: {
        headerBg: "#2a1418",
        rowHover: "#F43F5E",
        rowAlternate: "#1a0a0e",
        selectedRow: "#3b1a20",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#fb7185",
        info: "#60a5fa",
        neutral: "#9ca3af",
      },
    },
  },

  // 🧊 21. Frost Gray
  frost: {
    light: {
      primary: "#64748B",
      primaryForeground: "#ffffff",
      secondary: "#E2E8F0",
      secondaryForeground: "#1e293b",
      background: "#F8FAFC",
      foreground: "#0f172a",
      muted: "#F1F5F9",
      mutedForeground: "#64748b",
      border: "#e2e8f0",
      table: {
        headerBg: "#F1F5F9",
        rowHover: "#E2E8F0",
        rowAlternate: "#fafafa",
        selectedRow: "#e2e8f0",
      },
      brand: {
        success: "#22c55e",
        warning: "#f59e0b",
        danger: "#ef4444",
        info: "#64748B",
        neutral: "#64748b",
      },
    },
    dark: {
      primary: "#94A3B8",
      primaryForeground: "#000000",
      secondary: "#1E293B",
      secondaryForeground: "#F1F5F9",
      background: "#020617",
      foreground: "#E2E8F0",
      muted: "#0f172a",
      mutedForeground: "#94a3b8",
      border: "#1e293b",
      table: {
        headerBg: "#0f172a",
        rowHover: "#334155",
        rowAlternate: "#020617",
        selectedRow: "#1e293b",
      },
      brand: {
        success: "#22c55e",
        warning: "#fbbf24",
        danger: "#f87171",
        info: "#94a3b8",
        neutral: "#94a3b8",
      },
    },
  },
};

export type PaletteName = keyof typeof palettes;
